// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mensa.sql

package repository

import (
	"context"
)

const insertMensa = `-- name: InsertMensa :one
WITH ins AS (
    INSERT INTO mensa (name, description, slug, uuid, address_latitude, address_longitude, provider_id)
        SELECT $1, $2, $3, $5::text, 0, 0, $4
        WHERE NOT EXISTS (
            SELECT 1 FROM mensa
            WHERE uuid = $5::text
        )
        RETURNING id
)
SELECT id FROM ins
UNION
SELECT id FROM mensa WHERE uuid = $5::text AND provider_id = $4
`

type InsertMensaParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Slug        string  `json:"slug"`
	ProviderID  int32   `json:"provider_id"`
	Uuid        string  `json:"uuid"`
}

func (q *Queries) InsertMensa(ctx context.Context, arg InsertMensaParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertMensa,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.ProviderID,
		arg.Uuid,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
