// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: provider.sql

package repository

import (
	"context"
)

const insertMensaProvider = `-- name: InsertMensaProvider :one
WITH ins AS (
    INSERT INTO mensa_provider (name, description, slug, uuid)
        SELECT $1, $2, $3, $4::text
        WHERE NOT EXISTS (
            SELECT 1 FROM mensa_provider
            WHERE uuid = $4::text
        )
        RETURNING id
)
SELECT id FROM ins
UNION
SELECT id FROM mensa_provider WHERE uuid = $4::text
`

type InsertMensaProviderParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Slug        string `json:"slug"`
	Uuid        string `json:"uuid"`
}

func (q *Queries) InsertMensaProvider(ctx context.Context, arg InsertMensaProviderParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertMensaProvider,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Uuid,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
